language: perl
addons:
  apt:
    packages:
      - autoconf
      - zlib1g
      - zlib1g-dbg
      - zlib1g-dev
      - zlibc
      - libberkeleydb-perl
      - bioperl
perl:
  - "5.24-shrplib"
before_install:
  - export PERL5LIB=$PERL5LIB:$(pwd)/lib/perl5
    #- yes no | cpanm -l . Bio::Perl

