language: perl
addons:
  apt:
    packages:
      - autoconf
      - zlib1g
      - zlib1g-dbg
      - zlib1g-dev
      - zlibc
      - bioperl
perl:
  - "5.24-shrplib"
before_install:
  - yes no | cpanm -l . Bio::Perl

